import os
from pathlib import Path


def generate_issues(
    code_review: list,
    security: list,
    improvements: list,
) -> list[dict]:
    issues = []
    issue_num = 1

    for sec in security:
        if sec.get("severity") in ("critical", "high"):
            issues.append({
                "number": issue_num,
                "title": sec.get("message", "Security issue detected")[:80],
                "body": _format_issue_body(sec),
                "labels": ["security", sec.get("severity", "high")],
            })
            issue_num += 1

    for impr in improvements:
        if impr.get("priority") == "high":
            issues.append({
                "number": issue_num,
                "title": impr.get("suggestion", "Improvement needed")[:80],
                "body": f"## {impr.get('category', 'Improvement').title()}\n\n{impr.get('details', '')}\n\n**Suggested action:** {impr.get('suggestion', '')}",
                "labels": [impr.get("category", "enhancement"), "high-priority"],
            })
            issue_num += 1

    for cr in code_review:
        if cr.get("severity") in ("critical", "high"):
            issues.append({
                "number": issue_num,
                "title": cr.get("message", "Code quality issue")[:80],
                "body": _format_issue_body(cr),
                "labels": ["code-quality", cr.get("severity", "medium")],
            })
            issue_num += 1
            if issue_num > 10:
                break

    return issues[:10]


def _format_issue_body(item: dict) -> str:
    body = f"**File:** `{item.get('file', 'unknown')}`\n"
    if item.get("line"):
        body += f"**Line:** {item['line']}\n"
    body += f"\n**Description:**\n{item.get('message', 'No description')}\n"
    if item.get("recommendation"):
        body += f"\n**Recommendation:**\n{item['recommendation']}\n"
    body += "\n---\n*Generated by LgitLai*"
    return body
